repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
    exclude: &autofiles website/scripts/awards/
  - id: trailing-whitespace
    exclude: *autofiles
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    exclude: *autofiles
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
