repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
    exclude: &autofiles website/scripts/awards/
  - id: trailing-whitespace
    exclude: *autofiles
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    exclude: *autofiles
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: local
  hooks:
    - id: bats
      name: Run bats tests
      language: script
      entry: ./scripts/code/test_bats.sh
      pass_filenames: false
      require_serial: true
      args:
        - bats_tests/
