version: '3.7'
x-shared-envs:
  &shared_envs
  RCON_PASSWORD: "${RCON_PASSWORD:-minecraft}"
  TRACE: "true" # entrypoint
x-user:
  &user
  user: '1000:1000'
x-mc-common-settings:
  &mc_common_settings
  stop_grace_period: 12m
  working_dir: "/server"
x-jvm-image:
  &jvm_image
  image: server-manager
  build:
    context: .
  depends_on:
    - mariadb
x-mc-common-env:
  &mc_common_env
  JVM_FLAGS: |-
    -XX:+UseG1GC
    -XX:+ParallelRefProcEnabled
    -XX:+UnlockExperimentalVMOptions
    -XX:+DisableExplicitGC
    -XX:TargetSurvivorRatio=90
    -XX:-OmitStackTraceInFastThrow
    -XX:+AlwaysPreTouch
    -XX:MaxGCPauseMillis=100
    -XX:G1NewSizePercent=40
    -XX:G1MaxNewSizePercent=60
    -XX:G1ReservePercent=15
    -XX:G1HeapRegionSize=8M
    -XX:G1HeapWastePercent=5
    -XX:InitiatingHeapOccupancyPercent=20
    -XX:G1MixedGCLiveThresholdPercent=90
    -XX:G1RSetUpdatingPauseTimePercent=1
    -XX:SurvivorRatio=12
    -XX:MaxTenuringThreshold=1
    -DPaper.skipServerPropertiesComments=true

services:
  survival:
    <<: *user
    <<: *mc_common_settings
    <<: *jvm_image
    container_name: "survival"
    hostname: "survival"
    volumes:
      - './server-config/survival:/server'
    #restart: unless-stopped
    restart: "no"
    #command:
    #  - --forceUpgrade
    environment:
      <<: *shared_envs
      <<: *mc_common_env
      MEMORY: "${SURVIVAL_MEM?}"
      GIT_BRANCH: config_survival
    env_file:
      - ./.env-survival
      - ./.env
  creative-spawn:
    <<: *user
    <<: *mc_common_settings
    <<: *jvm_image
    container_name: "creative-spawn"
    hostname: "creative-spawn"
    volumes:
      - './server-config/creative-spawn:/server'
    #restart: unless-stopped
    restart: "no"
    #command:
    #  - --forceUpgrade
    environment:
      <<: *shared_envs
      <<: *mc_common_env
      MEMORY: "${CREATIVE_MEM?}"
      GIT_BRANCH: config_creative_spawn
    env_file:
      - ./.env-creative-spawn
      - ./.env
  velocity:
    <<: *user
    <<: *jvm_image
    container_name: "velocity"
    hostname: "velocity"
    working_dir: /velocity
    environment:
      JVM_FLAGS: |-
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=4M
        -XX:+UnlockExperimentalVMOptions
        -XX:+ParallelRefProcEnabled
        -XX:+AlwaysPreTouch
        -XX:MaxInlineLevel=15
      SERVER_JAR: server.jar
      MEMORY: "${PROXY_MEM?}"
      GIT_BRANCH: config_velocity
      DIRECT_EXEC: "true"
    volumes:
      - ./server-config/velocity:/velocity:rw
    ports:
      - 25565:25565
    env_file:
      - ./.env

  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: "mariadb"
    hostname: "mariadb"
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD?}"
      MARIADB_LUCKPERMS_PASSWORD: "${MARIADB_LUCKPERMS_PASSWORD?}"
      MARIADB_PRISM_PASSWORD: "${MARIADB_PRISM_PASSWORD?}"
    volumes:
      - './database-init/:/docker-entrypoint-initdb.d/:ro'

  website:
    <<: *user
    container_name: "website"
    hostname: "website"
    image: caddy:2.4.1-realip
    build:
      context: ./website
      args:
        CADDY_VERSION: 2.4.1
    restart: "no"
    ports:
      - 80:80
      - 443:443
    volumes:
      - './website/Caddyfile:/etc/caddy/Caddyfile:ro'
      - './website/files/src:/usr/share/caddy:ro'
      # Persist data
      - './website/config:/config:rw'
      - './website/data:/data:rw'
    environment:
      DOMAIN: "${DOMAIN?}"
  # MONITORING
  node_exporter:
    image: prom/node-exporter:v1.1.2
    restart: unless-stopped
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/host/var/tmp/textfiles'
      - '--collector.systemd'
      - '--collector.processes'
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($$|/)"
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
      - /run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro # Systemd collector
  docker_host: # For node_exporter
    image: qoomon/docker-host:2.5.5
    restart: unless-stopped
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
